name: 02 - Workflow Events

on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '25 7 * * 3,4,5'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "on"




